portfolio_analytics:
  target: local
  outputs:
    local:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH', '../artifacts/warehouse.duckdb') }}"
      threads: 4

elementary:
  target: local
  outputs:
    local:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH', '../artifacts/warehouse.duckdb') }}"
      schema: main_elementary
      threads: 4
